/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/16ed2fab-5c39-4c29-8429-2cf6741f2ef8 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float gyro_y;
  int counter;
  bool doorChange;
  bool reset_counter;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Arduino_MKRIoTCarrier.h>
MKRIoTCarrier carrier;
 
int pir = A5;
int pirState = LOW;
 
float gyro_x;
float gyro_z;
 
//Colors (Green, Red, Blue)
uint32_t colorGreen = carrier.leds.Color(255 , 0 ,0);
uint32_t colorBlue = carrier.leds.Color( 0 , 0 , 255);
uint32_t colorRed = carrier.leds.Color( 0 , 255 , 0);

 
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  
  pinMode(pir, INPUT);
  
   // Defined in thingProperties.h
  initProperties();
  
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  CARRIER_CASE = false;
  carrier.begin();
  
  setDebugMessageLevel(4);   //Get Cloud Info/errors , 0 (only errors) up to 4
  ArduinoCloud.printDebugInfo();
  
  while (ArduinoCloud.connected() != 1) {
    ArduinoCloud.update();
    carrier.display.setTextSize(3);
    carrier.display.setCursor(20, 70);
    carrier.display.println("Waiting For");
    carrier.display.setCursor(5, 110);
    carrier.display.println("Connection...");
    delay(500);
  }
 
 
 
 
  
}

void loop() {
 
  ArduinoCloud.update();
 
  carrier.IMUmodule.readGyroscope(gyro_x, gyro_y, gyro_z); //read the rotation values on the three axis
  pirState = digitalRead(pir); //read the values sent from the pir sensor
 
  carrier.display.fillScreen(ST77XX_BLACK); //set the background color of the display to black
  carrier.display.setTextSize(3); //set the size of the text to 3 (medium)
  carrier.display.setCursor(50, 50); //set the cursor at position x=50, y=100
  
  carrier.display.print("Y= ");
  carrier.display.print(gyro_y);
  
  
  if(gyro_y > 50 || gyro_y < -50)
  {
    doorChange = !doorChange;
  }
  
  
  if(doorChange == true) {
    
    carrier.display.setCursor(20, 150); //set the cursor at position x=20, y=150
    carrier.display.println("Door Opened");
    
    if(pirState == HIGH) {  
      counter += 1;
      
      //if movement is detected after opening the door, the RGBs will turn blue
      carrier.leds.fill(colorBlue, 0, 5);
      carrier.leds.show();
    }else{
    //if the door is opened without detecting movement, the RGBs will turn green
      carrier.leds.fill(colorGreen, 0 , 5);
      carrier.leds.show();
    }  
  }else{
    
    carrier.display.setCursor(20, 150); //set the cursor at position x=20, y=150
    carrier.display.print("Door Closed");
    
    //if the door has not been moved, the LEDs will turn red
    carrier.leds.fill(colorRed, 0 , 5);
    carrier.leds.show();
  }
  delay(500);
}
  









/*
  Since GyroY is READ_WRITE variable, onGyroYChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onGyroYChange()  {
  // Add your code here to act upon GyroY change
}

/*
  Since DoorChange is READ_WRITE variable, onDoorChangeChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onDoorChangeChange()  {
  // Add your code here to act upon DoorChange change
}

/*
  Since Counter is READ_WRITE variable, onCounterChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCounterChange()  {
  // Add your code here to act upon Counter change
}

/*
  Since ResetCounter is READ_WRITE variable, onResetCounterChange() is
  executed every time a new value is received from IoT Cloud.
*/
  

void onResetCounterChange() {
  counter = 0;
  
  carrier.Buzzer.sound(1000);
  delay(1000);
  carrier.Buzzer.noSound();
  delay(1500);
  
  reset_counter = false;
}



