/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/5b3dbe8d-3c14-49f1-9b4e-b3f50aff359c 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String message;
  CloudColoredLight rgb;
  int screenColor;
  int textSize;
  bool warningAlarm;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Arduino_MKRIoTCarrier.h>
MKRIoTCarrier carrier;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // Defined in thingProperties.h
  initProperties();
  
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  CARRIER_CASE = false;
  carrier.begin();
  
  setDebugMessageLevel(4);   //Get Cloud Info/errors , 0 (only errors) up to 4
  ArduinoCloud.printDebugInfo();
  
  while (ArduinoCloud.connected() != 1) {
    ArduinoCloud.update();
    carrier.display.setTextSize(3);
    carrier.display.setCursor(20, 70);
    carrier.display.println("Waiting For");
    carrier.display.setCursor(5, 110);
    carrier.display.println("Connection...");
    delay(500);
  }
}
void loop() {
  ArduinoCloud.update();
  // Your code here
  if (warningAlarm == true) {
    alarm();
  }
 
  carrier.display.setCursor(50, 100);
 
  //if (soundOn == true) {
    // carrier.Buzzer.sound(soundFrequency);
    // delay(soundDuration);
    //carrier.Buzzer.noSound();
    //delay(soundDuration);
  //}
 
}

void alarm() {
  carrier.display.fillScreen(ST77XX_RED); //set the background color of the screen to red
  carrier.display.setTextColor(ST77XX_WHITE); //set the color of the text to white
  carrier.display.setTextSize(3); //set the size of the text to 3 (medium)
  carrier.display.setCursor(50, 100); //set the cursor at position x=50, y=100
  carrier.display.print("WARNING!"); //display "WARNING!" on the screen
  //carrier.Buzzer.sound(1000); //turn on the sound buzzer with frequency=1000
  
  delay(1000); // wait for 1 second
 
  carrier.display.fillScreen(ST77XX_WHITE); //set the background color of the screen to white
  carrier.display.setTextColor(ST77XX_RED); //set the color of the text to red
  carrier.display.setCursor(50, 100); //set the cursor at position x=50, y=100
  carrier.display.print("WARNING!"); //display "WARNING!" on the screen
  //carrier.Buzzer.noSound();  //turn off the sound buzzer
  
  delay(1000); // wait for 1 second
  
  carrier.display.fillScreen(ST77XX_WHITE); //set screen to white
  carrier.display.setTextColor(ST77XX_WHITE); //set text to white
}

void backgroundColor() {
  
  switch (screenColor) {
    case 0:
      //if number's value is 0, execute code here
      carrier.display.fillScreen(ST77XX_BLACK);
      carrier.display.setTextColor(ST77XX_WHITE); //set the color of the text to WHITE
      break;
  
    case 1:
      //if number's value is 1, execute code here
      carrier.display.fillScreen(ST77XX_RED);
      carrier.display.setTextColor(ST77XX_WHITE); //set the color of the text to WHITE
      break;
      
    case 2:
      //if number's value is 2, execute code here
      carrier.display.fillScreen(ST77XX_YELLOW);
      carrier.display.setTextColor(ST77XX_BLACK); //set the color of the text to BLACK
      break;
      
    case 3:
      //if number's value is 3, execute code here
      carrier.display.fillScreen(ST77XX_ORANGE);
      carrier.display.setTextColor(ST77XX_WHITE); //set the color of the text to WHITE
      break;
      
    case 4:
      //if number's value is 4, execute code here
      carrier.display.fillScreen(ST77XX_GREEN);
      carrier.display.setTextColor(ST77XX_BLACK); //set the color of the text to BLACK
      break;
      
    case 5:
      //if number's value is 5, execute code here
      carrier.display.fillScreen(ST77XX_BLUE);
      carrier.display.setTextColor(ST77XX_WHITE); //set the color of the text to WHITE
      break;
      
    case 6:
      //if number's value is 6, execute code here
      carrier.display.fillScreen(ST77XX_MAGENTA);
      carrier.display.setTextColor(ST77XX_WHITE); //set the color of the text to WHITE
      break;
  }
 
}


/*
  Since SoundOn is READ_WRITE variable, onSoundOnChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSoundOnChange()  {
  // Add your code here to act upon SoundOn change
}

/*
  Since Message is READ_WRITE variable, onMessageChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMessageChange() {
  // Do something
  backgroundColor();
  carrier.display.setTextSize(textSize);
  carrier.display.println(message);
}
 
void onScreenColorChange() {
  // Do something
  backgroundColor();
  carrier.display.setTextSize(textSize);
  carrier.display.println(message);
}
 

/*
  Since WarningAlarm is READ_WRITE variable, onWarningAlarmChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onWarningAlarmChange()  {
  // Add your code here to act upon WarningAlarm change
}

/*
  Since Rgb is READ_WRITE variable, onRgbChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onRgbChange() {
  // Do something
  uint8_t r, g, b;
  rgb.getValue().getRGB(r, g, b);
  
  if (rgb.getSwitch()){
    
    for(int i=0; i<= 4 ; i++){
      carrier.leds.setPixelColor(i, g, r, b);
    }
    
    carrier.leds.show();
    
  }else{
    
    for(int i=0; i<= 4 ; i++){
      carrier.leds.setPixelColor(i,0);
    }
    
    carrier.leds.show();
  }
}


/*
  Since TextSize is READ_WRITE variable, onTextSizeChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTextSizeChange()  {
  backgroundColor();
  carrier.display.setTextSize(textSize);
  carrier.display.println(message);
}

